AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Meaningful Backend - Serverless application for scheduling calls with friends'

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment stage
  
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    NoEcho: true
  
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret  
    NoEcho: true
  
  FrontendUrl:
    Type: String
    Default: 'http://localhost:3000'
    Description: Frontend URL for OAuth redirects

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Environment:
      Variables:
        STAGE: !Ref Stage
        USERS_TABLE: !Ref UsersTable
        CALENDARS_TABLE: !Ref CalendarsTable
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
        FRONTEND_URL: !Ref FrontendUrl
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # API Gateway
  MeaningfulApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda Functions
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handlers.auth.handler
      Events:
        GoogleAuth:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /auth/google
            Method: GET
        AuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /auth/callback
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  CalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handlers.calendar.handler
      Events:
        CalendarSync:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /calendar/sync
            Method: POST
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /calendar/events
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarsTable

  AvailabilityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handlers.availability.handler
      Events:
        GetAvailability:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /users/{user_id}/availability
            Method: GET
        UpdateAvailability:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /users/{user_id}/availability
            Method: PUT
        OptionsAvailability:
          Type: Api
          Properties:
            RestApiId: !Ref MeaningfulApi
            Path: /users/{user_id}/availability
            Method: OPTIONS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'meaningful-${Stage}-users'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  CalendarsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'meaningful-${Stage}-calendars'
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: calendar_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: calendar_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${MeaningfulApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
    Export:
      Name: !Sub 'meaningful-${Stage}-api-url'
  
  ApiUrl:
    Description: 'API URL for OAuth redirects'
    Value: !Sub 'https://${MeaningfulApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
    Export:
      Name: !Sub 'meaningful-${Stage}-api-base-url'
  
  UsersTableName:
    Description: 'DynamoDB Users table name'
    Value: !Ref UsersTable
    Export:
      Name: !Sub 'meaningful-${Stage}-users-table'
  
  CalendarsTableName:
    Description: 'DynamoDB Calendars table name'
    Value: !Ref CalendarsTable
    Export:
      Name: !Sub 'meaningful-${Stage}-calendars-table'